// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

struct FLineVertex
{
	float Position;
	int32 Index;
	FLineVertex(const float InPosition, const int32 InIndex) : Position(InPosition), Index(InIndex) {}
};

struct FLineElement
{
	// Explicit constructor since we need to populate the Range value
 // 显式构造函数，因为我们需要填充 Range 值
	explicit FLineElement(const FLineVertex& InStart, const FLineVertex& InEnd) : Start(InStart), End(InEnd), bIsFirst(false), bIsLast(false)
	{
		Range = End.Position - Start.Position;
	}

	bool PopulateElement(const float ElementPosition, struct FEditorElement& InOutElement) const;
	bool IsBlendInputOnLine(const FVector& BlendInput) const
	{
		return (BlendInput.X >= Start.Position) && (BlendInput.X <= End.Position);
	}

	const FLineVertex Start;
	const FLineVertex End;
	bool bIsFirst;
	bool bIsLast;
	float Range;
};

/** Generates a line list between the supplied sample points to
aid blend space sample generation */
class FLineElementGenerator
{
public:
	void Init(const struct FBlendParameter& BlendParameter);

	void Process();

	/** 根据之前提供给 AddSamplePoint 的采样点填充 EditorElements */
	/** 根据之前提供给 AddSamplePoint 的采样点填充 EditorElements */
	/** Populates EditorElements based on the Sample points previously supplied to AddSamplePoint */
	/** 根据之前提供给 AddSamplePoint 的采样点填充 EditorElements */
	void CalculateEditorElements();
	
	/**
	 * Converts from our internal representation to the runtime segments
	 */
	TArray<struct FBlendSpaceSegment> CalculateSegments() const;

	/**
	* Data Structure for line generation
	* SamplePointList is the input data
	*/
	TArray<FLineVertex> SamplePointList;
	/** 由CalculateEditorElements生成的编辑器元素 */
	/** 由CalculateEditorElements生成的编辑器元素 */

	/** Editor elements generated by CalculateEditorElements */
	/** 由CalculateEditorElements生成的编辑器元素 */
	TArray<struct FEditorElement> EditorElements;
	/** 定义编辑器的范围 */

	/** 定义编辑器的范围 */
private:

	/** 我们必须为其生成 FEditorElements 的点数 */
	/** Defines the range of the editor */
	/** 定义编辑器的范围 */
	/** 我们必须为其生成 FEditorElements 的点数 */
	float MinGridValue;
	/** 从给定样本生成的线元素 */
	float MaxGridValue;

	/** Number of points that we have to generate FEditorElements for */
	/** 从给定样本生成的线元素 */
	/** 我们必须为其生成 FEditorElements 的点数 */
	int32 NumGridPoints;
	int32 NumGridDivisions;

	/** Line elements generated from the given samples */
	/** 从给定样本生成的线元素 */
	TArray<FLineElement> LineElements;
};
